ginkgo: Define TARGET_GRALLOC_HANDLE_HAS_RESERVED_SIZE
- Updated display stack requires to use GRALLOC_HANDLE_HAS_RESERVED_SIZE

[Reference]:
- VoidUI-Tiramisu/vendor_aosp@6e92cbb
- VoidUI-Tiramisu/vendor_qcom_opensource_commonsys-intf_display@063620a
- VoidUI-Tiramisu/vendor_qcom_opensource_commonsys-intf_display@7d4de03

[Fixing following errors]:
hardware/qcom-caf/sm8150/display/gralloc/gr_buf_mgr.cpp:107:43: error: no member named 'reserved_size' in 'private_handle_t'
  uint64_t reserved_region_size = handle->reserved_size;
                                  ~~~~~~  ^
hardware/qcom-caf/sm8150/display/gralloc/gr_buf_mgr.cpp:125:45: error: no member named 'reserved_size' in 'private_handle_t'
    uint64_t reserved_region_size = handle->reserved_size;
                                    ~~~~~~  ^
hardware/qcom-caf/sm8150/display/gralloc/gr_buf_mgr.cpp:752:41: error: no member named 'reserved_size' in 'private_handle_t'
  auto meta_size = getMetaDataSize(hnd->reserved_size);
                                   ~~~  ^
hardware/qcom-caf/sm8150/display/gralloc/gr_buf_mgr.cpp:1087:8: error: no member named 'reserved_size' in 'private_handle_t'
  hnd->reserved_size = descriptor.GetReservedSize();
  ~~~  ^
4 errors generated.

Signed-off-by: Christopher <mizdrake7@gmail.com>